# Hourly scraping
name: sitemap_scraping

# Triggers - Controls when the action will run.
on:
  schedule:
    - cron:  '0 */4 * * *' # Runs every 5 minutes

jobs: 
  autotime: # Job Name
    runs-on: macos-latest 

    # Load repo and install R
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      # Set-up R
      - name: Setup R 
        uses: r-lib/actions/setup-r@v2 # R setup action (version is important like v2)
        
      # Install dependency 
      - name: Install packages
        run: |
          R -e 'install.packages("tidyverse")'
          R -e 'install.packages("lubridate")'
          R -e 'install.packages("httr")'
          R -e 'install.packages("jsonlite")'
          
      # Run R script
      - name: Scrape
        run: Rscript gaction_test.R
      
      # Add new files in data folder, commit along with other modified files, push in same repo
      # ${GITHUB_REF##*/} - used to pick branch name automatically
      # REPO_KEY - used to authenticate push
      - name: Commit files
        run: |
          git pull
          git add data/*
          git commit -am "GH ACTION Headlines $(date)"
          git push origin ${GITHUB_REF##*/}
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
